### ISSUE TITLE
unknown action "undefined"

### ISSUE THREAD

**Issue by wuuer** [kevinheavey/anchor-bankrun#18]
Error: unknown action "undefined" 
occurs when calling a method of a contract throwing errors

It might be a bug related to "sendWithErr" function in index.js

**Comment by kevinrodriguez-io** [comment]
Getting this too. Any ideas?

**Comment by kevinheavey** [comment]
Can I get a reproducible example please?

**Comment by elo-siema** [comment]
Also getting this. Makes it impossible to test anchor errors like this:
https://solana.stackexchange.com/a/1619

**Comment by kevinheavey** [comment]
fixed by #19
